### ISSUE TITLE
Error when trying to use the visual editor

### ISSUE THREAD

**Issue by ReplicaObscura** [a-p-z/datetime-card#15]
When I try to add or edit this card, it won't allow me to go to the visual editor, and it shows this error below the yaml editor that appears:

```
Configuration errors detected:
<datetime-card-editor>: Cannot set read-only property 'setConfig'
```

I've tried configuring the card in yaml, then closing and re-editing it, and it throws the same error and skips right to the yaml editor.

**Comment by a-p-z** [comment]
NOTE: [lovelace-card-mod](https://github.com/thomasloven/lovelace-card-mod) and [lovelace-layout-card](https://github.com/thomasloven/lovelace-layout-card) makes the visual editor crash because it tries to overwrite setConfig method, which in datetime-card is read-only. The code editor works, just ignore the error.

Do you have any of these card installed?
