### ISSUE TITLE
<datetime-card-editor>: Cannot set read-only property 'setConfig'

### ISSUE THREAD

**Issue by monstergubl** [a-p-z/datetime-card#21]
Only yaml editor is available.

**Comment by a-p-z** [comment]
Hi @monstergubl. Can you provide more details?

**Comment by a-p-z** [comment]
NOTE: [lovelace-card-mod](https://github.com/thomasloven/lovelace-card-mod) and [lovelace-layout-card](https://github.com/thomasloven/lovelace-layout-card) makes the visual editor crash because it tries to overwrite setConfig method, which in datetime-card is read-only. The code editor works, just ignore the error.


do you have any of these card installed?

**Comment by hartitman** [comment]
Hi, I seem to be getting the following error since HA November update. the result is, it does not show the number of days.

Configuration errors detected:
<datetime-card-editor>: Cannot set read-only property 'setConfig'

**Comment by a-p-z** [comment]
fixed in v1.0.4
